version: "3.2"
services:
  minetest_server:
    image: miney/miney-server
    ports:
      - "29999:29999/tcp"
      - "30000:30000/udp"
    environment:
      MT_MAX_USERS: 200
      MT_MG_NAME: flat
      MT_MG_FLAGS: nocaves,nodungeons,light,nodecorations,biomes
      MT_MGFLAT_GROUND_LEVEL: -1
      MT_WATER_LEVEL: -2
      MT_CREATIVE_MODE: "true"
      MT_STATIC_SPAWNPOINT: (0,0,0)

  minetest_client:
    image: miney/minetest-client
    depends_on:
      - "minetest_server"
    environment:
      SERVER: minetest_server
      PORT: 30000
      PLAYERNAME: RANDOM
      RANDOM_INPUT: 1
##      VNC: 1
#    ports:
#      - "5901:5901/tcp"
